#!/usr/bin/env python3
"""Prepare the TM5S + 2FG7 model for Isaac Sim and standalone cuMotion.

The input is the combined dry-run URDF generated by
``build_tm5s_2fg7_urdf.py``.  This script stages all referenced meshes beside
an import-safe URDF, removes ROS/Gazebo-only tags, and builds an XRDF collision
sphere model with NVIDIA cuMotion's sphere generator.

The resulting model remains an offline approximation until the physical quick
changer, flange-to-gripper mount, TCP, and controller jerk limits are measured.
"""

from __future__ import annotations

import argparse
import json
import math
import shutil
import xml.etree.ElementTree as ET
from pathlib import Path
from urllib.parse import unquote, urlparse

import cumotion
import numpy as np
import trimesh
import yaml


ARENA_DIR = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ARENA_DIR / "generated/tm5s_with_2fg7.urdf"
DEFAULT_OUTPUT_DIR = ARENA_DIR / "generated/cumotion"
MOVING_JOINTS = [f"joint_{index}" for index in range(1, 7)]
ARTICULATED_FINGER_JOINTS = [
    "onrobot_2fg7_left_finger_joint",
    "onrobot_2fg7_right_finger_joint",
]
DEFAULT_JOINT_POSITIONS = [0.0, 0.0, 1.5708, 0.0, 1.5708, 0.0]
ACCELERATION_LIMITS = [2.0, 2.0, 2.0, 2.5, 2.5, 4.0]
# Offline-only provisional limits. Replace these with controller-approved data.
PROVISIONAL_JERK_LIMITS = [20.0, 20.0, 20.0, 25.0, 25.0, 40.0]
REQUIRED_SPHERES_PER_LINK = {
    "link_0": 12,
    "link_1": 16,
    "link_2": 24,
    "link_3": 24,
    "link_4": 16,
    "link_5": 16,
    "link_6": 16,
    "onrobot_2fg7_base_link": 24,
    "onrobot_2fg7_left_finger_link": 12,
    "onrobot_2fg7_right_finger_link": 12,
}
OPTIONAL_SPHERES_PER_LINK = {
    "onrobot_qc_robot_side_link": 12,
}
SEMANTIC_TOOL_FRAMES = [
    "flange",
    "onrobot_nominal_tcp",
    "finger_tip_plane",
    "pin_grasp_tcp",
    "gripper_tcp",
]
SELF_COLLISION_IGNORE = {
    "link_0": ["link_1"],
    "link_1": ["link_2", "link_3", "link_4"],
    "link_2": ["link_3"],
    "link_3": ["link_4"],
    "link_4": ["link_5", "link_6"],
    "link_5": ["link_6"],
    "link_6": ["onrobot_2fg7_base_link"],
    "onrobot_2fg7_base_link": [
        "onrobot_2fg7_left_finger_link",
        "onrobot_2fg7_right_finger_link",
    ],
}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument(
        "--asset-mode",
        choices=["planning", "isaac_articulated"],
        default="planning",
        help=(
            "Prepare the six-axis cuMotion planning bundle, or stage the exact "
            "two additional prismatic finger joints for a separate Isaac-only asset."
        ),
    )
    parser.add_argument(
        "--tm-description-share",
        type=Path,
        default=None,
        help="Path to tm_description/share/tm_description for package:// resolution.",
    )
    parser.add_argument(
        "--sphere-radius-offset",
        type=float,
        default=0.002,
        help="Safety expansion applied to generated collision spheres, metres.",
    )
    parser.add_argument(
        "--surface-coverage-margin",
        type=float,
        default=0.001,
        help=(
            "Required margin around collision-mesh vertices and the deterministic sampled "
            "surface set. Individual spheres are expanded to meet this sampled audit, metres; "
            "this is not a proof of complete mesh enclosure."
        ),
    )
    parser.add_argument(
        "--surface-samples-per-link",
        type=int,
        default=20000,
        help="Deterministic collision-mesh surface samples used for sphere coverage checks.",
    )
    return parser


def find_tm_description_share(explicit: Path | None) -> Path:
    candidates = []
    if explicit is not None:
        candidates.append(explicit)
    candidates.extend(
        [
            Path.home() / "tm2_ws_apt/install/tm_description/share/tm_description",
            Path.home() / "tm2_ws/install/tm_description/share/tm_description",
            Path("/opt/ros/jazzy/share/tm_description"),
        ]
    )
    for candidate in candidates:
        if candidate.is_dir():
            return candidate.resolve()
    raise FileNotFoundError(
        "Could not locate tm_description. Pass --tm-description-share explicitly."
    )


def resolve_mesh_uri(uri: str, urdf_dir: Path, tm_description_share: Path) -> tuple[Path, Path]:
    """Return source path and deterministic relative staging path."""
    if uri.startswith("package://"):
        package_path = uri.removeprefix("package://")
        package_name, separator, relative = package_path.partition("/")
        if not separator or package_name != "tm_description":
            raise ValueError(f"Unsupported package mesh URI: {uri}")
        return tm_description_share / relative, Path("tm_description") / relative

    if uri.startswith("file://"):
        source = Path(unquote(urlparse(uri).path))
    else:
        source = Path(uri)
        if not source.is_absolute():
            source = urdf_dir / source

    source = source.resolve()
    vendor_root = ARENA_DIR / "vendor/onrobot_2fg7"
    try:
        relative = source.relative_to(vendor_root.resolve())
        return source, Path("onrobot_2fg7") / relative
    except ValueError:
        return source, Path("external") / source.name


def stage_obj_materials(source: Path, destination: Path) -> None:
    text = destination.read_text(encoding="utf-8", errors="replace")
    output_lines: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped.startswith("mtllib "):
            output_lines.append(line)
            continue

        referenced_name = stripped.split(maxsplit=1)[1]
        referenced_source = source.parent / referenced_name
        if referenced_source.exists():
            material_source = referenced_source
        else:
            material_source = source.with_suffix(".mtl")

        if material_source.exists():
            shutil.copy2(material_source, destination.parent / material_source.name)
            indentation = line[: len(line) - len(line.lstrip())]
            output_lines.append(f"{indentation}mtllib {material_source.name}")
        else:
            output_lines.append(line)

    destination.write_text("\n".join(output_lines) + "\n", encoding="utf-8")


def stage_meshes(
    root: ET.Element,
    input_urdf: Path,
    output_dir: Path,
    tm_description_share: Path,
) -> dict[str, str]:
    mesh_dir = output_dir / "meshes"
    manifest: dict[str, str] = {}
    for mesh in root.findall(".//mesh"):
        uri = mesh.get("filename")
        if not uri:
            continue
        source, relative = resolve_mesh_uri(uri, input_urdf.parent, tm_description_share)
        if not source.is_file():
            raise FileNotFoundError(f"Referenced mesh does not exist: {source}")

        destination = mesh_dir / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
        if source.suffix.lower() == ".obj":
            stage_obj_materials(source, destination)

        staged_uri = (Path("meshes") / relative).as_posix()
        mesh.set("filename", staged_uri)
        manifest[uri] = staged_uri
    return manifest


def strip_non_isaac_tags(root: ET.Element) -> list[str]:
    removed: list[str] = []
    for child in list(root):
        if child.tag in {"gazebo", "transmission", "ros2_control"}:
            removed.append(child.tag)
            root.remove(child)
    return removed


def parse_vector(value: str | None, default: tuple[float, float, float]) -> np.ndarray:
    if value is None:
        return np.asarray(default, dtype=np.float64)
    vector = np.fromstring(value, sep=" ", dtype=np.float64)
    if vector.shape != (3,):
        raise ValueError(f"Expected three values, got: {value!r}")
    return vector


def rpy_rotation_matrix(rpy: np.ndarray) -> np.ndarray:
    roll, pitch, yaw = rpy
    cr, sr = math.cos(roll), math.sin(roll)
    cp, sp = math.cos(pitch), math.sin(pitch)
    cy, sy = math.cos(yaw), math.sin(yaw)
    return np.array(
        [
            [cy * cp, cy * sp * sr - sy * cr, cy * sp * cr + sy * sr],
            [sy * cp, sy * sp * sr + cy * cr, sy * sp * cr - cy * sr],
            [-sp, cp * sr, cp * cr],
        ],
        dtype=np.float64,
    )


def collision_mesh_for_link(link: ET.Element, urdf_dir: Path) -> tuple[np.ndarray, np.ndarray] | None:
    all_vertices: list[np.ndarray] = []
    all_faces: list[np.ndarray] = []
    vertex_offset = 0

    for collision in link.findall("collision"):
        geometry = collision.find("geometry")
        if geometry is None:
            continue
        mesh_element = geometry.find("mesh")
        box_element = geometry.find("box")
        cylinder_element = geometry.find("cylinder")
        sphere_element = geometry.find("sphere")
        if mesh_element is not None and mesh_element.get("filename"):
            mesh_path = (urdf_dir / mesh_element.get("filename", "")).resolve()
            triangle_mesh = trimesh.load_mesh(mesh_path, process=False)
            if isinstance(triangle_mesh, trimesh.Scene):
                triangle_mesh = triangle_mesh.to_mesh()
            vertices = np.asarray(triangle_mesh.vertices, dtype=np.float64)
            faces = np.asarray(triangle_mesh.faces, dtype=np.int32)
            scale = parse_vector(mesh_element.get("scale"), (1.0, 1.0, 1.0))
            vertices = vertices * scale
        elif box_element is not None:
            extents = parse_vector(box_element.get("size"), (0.0, 0.0, 0.0))
            triangle_mesh = trimesh.creation.box(extents=extents)
            vertices = np.asarray(triangle_mesh.vertices, dtype=np.float64)
            faces = np.asarray(triangle_mesh.faces, dtype=np.int32)
        elif cylinder_element is not None:
            radius = float(cylinder_element.get("radius", "0"))
            height = float(cylinder_element.get("length", "0"))
            triangle_mesh = trimesh.creation.cylinder(radius=radius, height=height, sections=64)
            vertices = np.asarray(triangle_mesh.vertices, dtype=np.float64)
            faces = np.asarray(triangle_mesh.faces, dtype=np.int32)
        elif sphere_element is not None:
            radius = float(sphere_element.get("radius", "0"))
            triangle_mesh = trimesh.creation.icosphere(subdivisions=3, radius=radius)
            vertices = np.asarray(triangle_mesh.vertices, dtype=np.float64)
            faces = np.asarray(triangle_mesh.faces, dtype=np.int32)
        else:
            continue

        origin = collision.find("origin")
        xyz = parse_vector(origin.get("xyz") if origin is not None else None, (0.0, 0.0, 0.0))
        rpy = parse_vector(origin.get("rpy") if origin is not None else None, (0.0, 0.0, 0.0))
        vertices = (rpy_rotation_matrix(rpy) @ vertices.T).T + xyz

        all_vertices.append(vertices)
        all_faces.append(faces + vertex_offset)
        vertex_offset += len(vertices)

    if not all_vertices:
        return None
    return np.vstack(all_vertices), np.vstack(all_faces)


def rounded(value: float) -> float:
    return float(f"{value:.9g}")


def generate_collision_spheres(
    root: ET.Element,
    urdf_dir: Path,
    radius_offset: float,
    coverage_margin: float,
    surface_samples_per_link: int,
) -> tuple[dict[str, list[dict[str, object]]], dict[str, dict[str, float | int]]]:
    geometry: dict[str, list[dict[str, object]]] = {}
    coverage_report: dict[str, dict[str, float | int]] = {}
    spheres_per_link = dict(REQUIRED_SPHERES_PER_LINK)
    for link_name, count in OPTIONAL_SPHERES_PER_LINK.items():
        if root.find(f"./link[@name='{link_name}']") is not None:
            spheres_per_link[link_name] = count
    for link_name, count in spheres_per_link.items():
        link = root.find(f"./link[@name='{link_name}']")
        if link is None:
            raise ValueError(f"Expected collision link is missing from URDF: {link_name}")
        mesh_data = collision_mesh_for_link(link, urdf_dir)
        if mesh_data is None:
            raise ValueError(f"Link has no mesh collision geometry: {link_name}")
        vertices, faces = mesh_data
        generator = cumotion.create_collision_sphere_generator(vertices, faces)
        raw_spheres = generator.generate_spheres(count, radius_offset)
        centers = np.asarray([sphere.center for sphere in raw_spheres], dtype=np.float64)
        radii = np.asarray([sphere.radius for sphere in raw_spheres], dtype=np.float64)

        audit_mesh = trimesh.Trimesh(vertices=vertices, faces=faces, process=False)
        surface_points, _ = trimesh.sample.sample_surface(
            audit_mesh,
            surface_samples_per_link,
            seed=790,
        )
        audit_points = np.vstack([vertices, surface_points])
        signed_gaps = (
            np.linalg.norm(audit_points[:, np.newaxis, :] - centers[np.newaxis, :, :], axis=2)
            - radii[np.newaxis, :]
        )
        nearest_sphere = np.argmin(signed_gaps, axis=1)
        raw_max_gap = float(np.min(signed_gaps, axis=1).max())
        expansions = np.zeros(len(raw_spheres), dtype=np.float64)
        for sphere_index in range(len(raw_spheres)):
            assigned_gaps = signed_gaps[nearest_sphere == sphere_index, sphere_index]
            if assigned_gaps.size:
                expansions[sphere_index] = max(
                    0.0,
                    float(assigned_gaps.max()) + coverage_margin,
                )
        radii += expansions
        covered_signed_gaps = (
            np.linalg.norm(audit_points[:, np.newaxis, :] - centers[np.newaxis, :, :], axis=2)
            - radii[np.newaxis, :]
        )
        covered_max_gap = float(np.min(covered_signed_gaps, axis=1).max())
        geometry[link_name] = [
            {
                "center": [rounded(float(component)) for component in center],
                "radius": rounded(float(radius)),
            }
            for center, radius in zip(centers, radii)
        ]
        coverage_report[link_name] = {
            "mesh_vertices": len(vertices),
            "surface_samples": len(surface_points),
            "sphere_count": len(raw_spheres),
            "raw_max_uncovered_gap_m": raw_max_gap,
            "maximum_applied_radius_expansion_m": float(expansions.max()),
            "audited_max_uncovered_gap_m": covered_max_gap,
        }
        if covered_max_gap > -coverage_margin + 1e-9:
            raise RuntimeError(
                f"Collision spheres for {link_name} did not meet the requested "
                f"coverage margin: max gap {covered_max_gap:.6g} m"
            )
    return geometry, coverage_report


def available_tool_frames(root: ET.Element) -> list[str]:
    link_names = {link.get("name") for link in root.findall("link")}
    return [frame for frame in SEMANTIC_TOOL_FRAMES if frame in link_names]


def self_collision_ignore(root: ET.Element) -> dict[str, list[str]]:
    ignore = {link: list(neighbours) for link, neighbours in SELF_COLLISION_IGNORE.items()}
    if root.find("./link[@name='onrobot_qc_robot_side_link']") is not None:
        # The QC is a thin rigid spacer. Its conservative spheres and the
        # attached gripper-base spheres overlap link_6 across the fixed stack,
        # so retain the legacy link_6/base exclusion as well as both direct
        # mechanical neighbours.
        ignore["link_6"].append("onrobot_qc_robot_side_link")
        ignore["onrobot_qc_robot_side_link"] = ["onrobot_2fg7_base_link"]
    return ignore


def write_xrdf(
    output_path: Path,
    spheres: dict[str, list[dict[str, object]]],
    tool_frames: list[str],
    ignored_pairs: dict[str, list[str]],
) -> None:
    xrdf = {
        "format": "xrdf",
        "format_version": 2.0,
        "default_joint_positions": dict(zip(MOVING_JOINTS, DEFAULT_JOINT_POSITIONS)),
        "cspace": {
            "joint_names": MOVING_JOINTS,
            "acceleration_limits": ACCELERATION_LIMITS,
            "jerk_limits": PROVISIONAL_JERK_LIMITS,
        },
        "tool_frames": tool_frames,
        "modifiers": [{"set_base_frame": "base"}],
        "world_collision": {"geometry": "tm5s_2fg7_collision_spheres"},
        "self_collision": {
            "geometry": "tm5s_2fg7_collision_spheres",
            "ignore": ignored_pairs,
        },
        "geometry": {
            "tm5s_2fg7_collision_spheres": {
                "spheres": spheres,
            }
        },
    }
    header = (
        "# Generated for camera-free offline benchmarking.\n"
        "# Jerk limits and unmeasured tool-frame values are provisional; do not use for hardware.\n"
    )
    output_path.write_text(
        header + yaml.safe_dump(xrdf, sort_keys=False, width=120),
        encoding="utf-8",
    )


def validate_moving_joints(root: ET.Element, expected: list[str] | None = None) -> list[str]:
    expected = MOVING_JOINTS if expected is None else expected
    moving = [
        joint.get("name", "")
        for joint in root.findall("joint")
        if joint.get("type") not in {"fixed", None}
    ]
    if moving != expected:
        raise ValueError(f"Expected exactly {expected}; found {moving}")
    return moving


def validate_articulated_finger_joints(root: ET.Element) -> None:
    leader_name, follower_name = ARTICULATED_FINGER_JOINTS
    leader = root.find(f"./joint[@name='{leader_name}']")
    follower = root.find(f"./joint[@name='{follower_name}']")
    if leader is None or follower is None:
        raise ValueError("Isaac articulated mode requires both reviewed 2FG7 finger joints")
    if leader.get("type") != "prismatic" or follower.get("type") != "prismatic":
        raise ValueError("Isaac articulated 2FG7 finger joints must be prismatic")
    if leader.find("mimic") is not None:
        raise ValueError("The left 2FG7 finger must remain the independent drive joint")
    mimic = follower.find("mimic")
    if (
        mimic is None
        or mimic.get("joint") != leader_name
        or float(mimic.get("multiplier", "nan")) != 1.0
        or float(mimic.get("offset", "0")) != 0.0
    ):
        raise ValueError("The right 2FG7 finger must mimic the left joint exactly")


def main() -> int:
    args = build_parser().parse_args()
    input_urdf = args.input.resolve()
    if not input_urdf.is_file():
        raise FileNotFoundError(
            f"Combined URDF not found: {input_urdf}\n"
            "Run scripts/build_tm5s_2fg7_urdf.py first."
        )

    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    tm_description_share = find_tm_description_share(args.tm_description_share)

    tree = ET.parse(input_urdf)
    root = tree.getroot()
    expected_moving_joints = list(MOVING_JOINTS)
    if args.asset_mode == "isaac_articulated":
        expected_moving_joints.extend(ARTICULATED_FINGER_JOINTS)
    moving_joints = validate_moving_joints(root, expected_moving_joints)
    if args.asset_mode == "isaac_articulated":
        validate_articulated_finger_joints(root)
    removed_tags = strip_non_isaac_tags(root)
    mesh_manifest = stage_meshes(root, input_urdf, output_dir, tm_description_share)
    ET.indent(tree, space="  ")

    output_urdf = output_dir / "tm5s_with_2fg7.urdf"
    tree.write(output_urdf, encoding="utf-8", xml_declaration=True)
    output_xrdf = output_dir / "tm5s_with_2fg7.xrdf"
    tool_frames = available_tool_frames(root)
    if args.asset_mode == "planning":
        spheres, coverage_report = generate_collision_spheres(
            root,
            output_dir,
            args.sphere_radius_offset,
            args.surface_coverage_margin,
            args.surface_samples_per_link,
        )
        ignored_pairs = self_collision_ignore(root)
        write_xrdf(output_xrdf, spheres, tool_frames, ignored_pairs)
    else:
        spheres = {}
        coverage_report = {}
        if output_xrdf.exists():
            output_xrdf.unlink()

    quick_changer_modeled = root.find("./link[@name='onrobot_qc_robot_side_link']") is not None
    warnings = [
        "XRDF jerk limits are provisional offline values.",
        "Mount yaw and application pin-grasp depth are uncalibrated.",
        "Collision-sphere coverage is sample-audited, not a certified conservative enclosure.",
        "2FG7/QC inertia values are simulation-only geometric proxies.",
    ]
    if not quick_changer_modeled:
        warnings.insert(0, "OnRobot Quick Changer is omitted by the selected tool profile.")

    manifest = {
        "source_urdf": str(input_urdf),
        "prepared_urdf": str(output_urdf),
        "xrdf": str(output_xrdf) if args.asset_mode == "planning" else None,
        "tm_description_share": str(tm_description_share),
        "asset_mode": args.asset_mode,
        "moving_joints": moving_joints,
        "tool_frame": "flange",
        "tool_frames": tool_frames,
        "quick_changer_collision_modeled": quick_changer_modeled,
        "collision_sphere_count": (
            sum(len(link_spheres) for link_spheres in spheres.values())
            if args.asset_mode == "planning"
            else None
        ),
        "sphere_radius_offset_m": args.sphere_radius_offset,
        "surface_coverage_margin_m": args.surface_coverage_margin,
        "surface_samples_per_link": args.surface_samples_per_link,
        "sphere_coverage_audit_scope": (
            "All collision-mesh vertices plus a deterministic sampled surface set; "
            "not a proof that the sphere union encloses every mesh point."
        ),
        "sphere_coverage_audit": coverage_report,
        "removed_root_tags": sorted(set(removed_tags)),
        "mesh_manifest": mesh_manifest,
        "offline_only": True,
        "warnings": warnings,
    }
    manifest_path = output_dir / "asset_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    print(f"Prepared URDF: {output_urdf}")
    if args.asset_mode == "planning":
        print(f"Generated XRDF: {output_xrdf}")
        print(f"Collision spheres: {manifest['collision_sphere_count']}")
    else:
        print("XRDF generation: skipped for Isaac-only articulated asset")
    print(f"Manifest: {manifest_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
